nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/jessesuen/otel-app
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: ""

replicaCount: 1

podAnnotations: {}
podLabels: {}

env:
  # LAMBDA_URL: https://xxxxxxxxxxxxxxxxx.lambda-url.us-west-2.on.aws/

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# Adds DataDog APM instrumentation (environment variables and labels) to
# to resources, and a host volume mount to the Datadog Agent APM socket.
datadog:
  enabled: true
  env: dev

service:
  type: ClusterIP
  port: 8080

serviceMonitor:
  enabled: false
  # Additional labels to add to the ServiceMonitor (e.g. for Prometheus operator label selectors)
  labels: {}
  interval: 30s

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: otel-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
    # - secretName: otel-app-tls
    #   hosts:
    #     - otel-app.local

httpRoute:
  # HTTPRoute enabled.
  enabled: false
  # HTTPRoute annotations.
  annotations: {}
  # Which Gateways this Route is attached to.
  parentRefs:
  - name: gateway
    sectionName: http
    # namespace: default
  # Hostnames matching HTTP header.
  hostnames:
  - otel-app.local
  # List of rules and filters applied.
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /headers
  #   filters:
  #   - type: RequestHeaderModifier
  #     requestHeaderModifier:
  #       set:
  #       - name: My-Overwrite-Header
  #         value: this-is-the-only-value
  #       remove:
  #       - User-Agent
  # - matches:
  #   - path:
  #       type: PathPrefix
  #       value: /echo
  #     headers:
  #     - name: version
  #       value: v2
