apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel-app.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otel-app.labels" . | nindent 4 }}
    {{- if .Values.datadog.enabled }}
    tags.datadoghq.com/env: {{ .Values.datadog.env }}
    tags.datadoghq.com/service: {{ include "otel-app.name" . }}
    tags.datadoghq.com/version: {{ include "otel-app.appVersion" . }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "otel-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "otel-app.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.datadog.enabled }}
        tags.datadoghq.com/env: {{ .Values.datadog.env }}
        tags.datadoghq.com/service: {{ include "otel-app.name" . }}
        tags.datadoghq.com/version: {{ include "otel-app.appVersion" . }}
        {{- end }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: otel-app
          image: "{{ .Values.image.repository }}:{{ include "otel-app.appVersion" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.env .Values.datadog.enabled }}
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          {{- if .Values.datadog.enabled }}
            - name: DD_ENV
              value: {{ .Values.datadog.env }}
            - name: DD_SERVICE
              value: {{ include "otel-app.name" . }}
            - name: DD_VERSION
              value: {{ include "otel-app.appVersion" . }}
          {{- end }}
          {{- end }}
          {{- if .Values.datadog.enabled }}
          volumeMounts:
            - mountPath: /var/run/datadog
              name: apmsocketpath
          {{- end }}
      {{- if .Values.datadog.enabled }}
      volumes:
        - hostPath:
            path: /var/run/datadog/
          name: apmsocketpath
      {{- end }}
